[project]
name = "backend"
version = "0.0.0"
description = "A self-hosted eBook server"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "en-core-web-sm",
  "fastapi[standard]>=0.138.2",
  "pikepdf>=10.7.0",
  "pymupdf>=1.27.2.3",
  "pymupdf4llm>=1.28.0",
  "requests>=2.34.2",
  "soundfile>=0.14.0",
  "spacy>=3.8.16",
  "sqlalchemy>=2.0.51",
  "xxhash>=3.7.0",
]

[project.optional-dependencies]
tts-kokoro = [
    "kokoro-onnx>=0.6.1",
]

[dependency-groups]
dev = [
    "scalar-fastapi>=1.9.0",
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = [
  "fastapi.Depends",
  "fastapi.Query",
  "fastapi.Path",
  "fastapi.Body"
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
